### ISSUE TITLE
Error when running bibtex

### ISSUE THREAD

**Issue by shawnps** [iamjakewarner/jdf#2]
Hi @iamjakewarner, thanks for making this repo.

I'm running the following:

`pdflatex jdf-starter && bibtex jdf-starter` and getting the following errors:

```
This is BibTeX, Version 0.99d (TeX Live 2019)
The top-level auxiliary file: jdf-starter.aux
I found no \citation commands---while reading file jdf-starter.aux
I found no \bibdata command---while reading file jdf-starter.aux
I found no \bibstyle command---while reading file jdf-starter.aux
(There were 3 error messages)
```

I was wondering if you've ever seen this before? Basically the citations and references aren't being generated properly.

**Comment by shawnps** [comment]
It seems I needed to run `biber jdf-starter`

**Comment by iamjakewarner** [comment]
I’m not sure what your workflow looks like, but I don’t have to run anything other than `pdflatex jdf-starter`. The `.cls` file instructs the compiler how to handle references.

Does it not work the same for you?

**Comment by shawnps** [comment]
@iamjakewarner unfortunately yes I have to run a separate command. Here's my current flow:

`pdflatex journal1 && biber journal1 && pdflatex journal1`

I have seen some other students in EdTech experiencing the same issue. Not sure what's up. Pretty sure I'm on latest of everything after updating in TeX Live:

```
➜  ~ bibtex --version
BibTeX 0.99d (TeX Live 2019)
kpathsea version 6.3.1
Copyright 2019 Oren Patashnik.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the BibTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the BibTeX source.
Primary author of BibTeX: Oren Patashnik.
```
