### ISSUE TITLE
Space after open paren when citing multiple authors?

### ISSUE THREAD

**Issue by shawnps** [iamjakewarner/jdf#3]
Hi @iamjakewarner, just wondering if this is intentional:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/80111/63829673-250e6d00-c9a5-11e9-8881-474ba5748dde.png">

You can see there is a space after the first paren when citing multiple authors.

**Comment by iamjakewarner** [comment]
Nope, not intentional. I’ll look into it when I get a chance. Do you have any ideas what might be causing it?

**Comment by shawnps** [comment]
@iamjakewarner thanks for responding, really appreciate you taking a look as I'm taking EdTech this semester and using this repo :)

Hmm, unfortunately I'm not sure what might be causing it, I'm quite a beginner with LaTeX. I will take a look at the `.cls` file. Did you write it from scratch or base it on an existing `.cls` file I could compare to?

**Comment by iamjakewarner** [comment]
I wrote it from scratch. The relevant section begins on line 210 of the `.cls` file. 

I’m sure it’s just a matter of inserting `\ignorespaces` somewhere. No worries if you’re not able to solve it, but I may not get around to it for a few days.

**Comment by shawnps** [comment]
@iamjakewarner thanks for the hint. I'll see if I come up with anything and let you know. First priority is for me to finish my assignment though :)

**Comment by shawnps** [comment]
@iamjakewarner hmm, this might be a LaTeX thing, rather than an issue with your class:

https://tex.stackexchange.com/questions/164847/how-do-you-remove-a-space-before-a-citation-in-latex

**Comment by shawnps** [comment]
@iamjakewarner I was able to fix this by changing:

`\renewcommand{\cite}[1]{ \citeauthor{#1}, \citeyear{#1}}`

to:

`\renewcommand{\cite}[1]{\citeauthor{#1}, \citeyear{#1}}`

**Comment by iamjakewarner** [comment]
I see. Good work!
